# -*- coding: utf-8 -*-
"""Movie_Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M0evPUZ_psAGBv8c1bPfLZw1VB_LA4L

# Smart Movie Recommendation System

**Student Name:** Vaishnavi Koya  
**Project Type:** Artificial Intelligence Recommendation System  
**Development Environment:** Google Colab  
**Programming Language:** Python  

## Project Overview

This project implements a content-based movie recommendation system using artificial intelligence and machine learning techniques. The system analyzes movie genres and descriptions using Term Frequency–Inverse Document Frequency (TF-IDF). It then calculates cosine similarity between movies to generate personalized recommendations based on a movie selected by the user.

The system includes an interactive interface that allows the user to select a movie, choose the desired number of recommendations, and generate a ranked recommendation list.
"""

# Install dependencies before running:
# pip install pandas scikit-learn ipywidgets

# Import the required libraries
import pandas as pd
import numpy as np
import ipywidgets as widgets

from IPython.display import display, clear_output
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("All required libraries were imported successfully.")

"""## 1. Movie Dataset

The dataset used in this project contains movie titles, genres, descriptions, ratings, and release years. The genre and description fields provide the textual information used by the content-based recommendation algorithm.
"""

movie_data = [
    {
        "title": "Interstellar",
        "genre": "Science Fiction Adventure Drama",
        "description": "A team of explorers travels through a wormhole in space to save humanity.",
        "rating": 8.7,
        "year": 2014
    },
    {
        "title": "The Martian",
        "genre": "Science Fiction Adventure Drama",
        "description": "An astronaut stranded on Mars uses science and determination to survive.",
        "rating": 8.0,
        "year": 2015
    },
    {
        "title": "Arrival",
        "genre": "Science Fiction Drama Mystery",
        "description": "A linguist communicates with mysterious visitors from another world.",
        "rating": 7.9,
        "year": 2016
    },
    {
        "title": "Gravity",
        "genre": "Science Fiction Thriller Drama",
        "description": "Two astronauts struggle to survive after an accident in space.",
        "rating": 7.7,
        "year": 2013
    },
    {
        "title": "Blade Runner 2049",
        "genre": "Science Fiction Mystery Drama",
        "description": "A futuristic police officer uncovers a secret that could change society.",
        "rating": 8.0,
        "year": 2017
    },
    {
        "title": "Avatar",
        "genre": "Science Fiction Adventure Fantasy",
        "description": "A former marine explores an alien world and becomes involved with its people.",
        "rating": 7.9,
        "year": 2009
    },
    {
        "title": "Inception",
        "genre": "Science Fiction Action Thriller",
        "description": "A skilled thief enters dreams to steal and implant information.",
        "rating": 8.8,
        "year": 2010
    },
    {
        "title": "The Dark Knight",
        "genre": "Action Crime Drama",
        "description": "A masked hero confronts a dangerous criminal mastermind.",
        "rating": 9.0,
        "year": 2008
    },
    {
        "title": "Iron Man",
        "genre": "Action Adventure Science Fiction",
        "description": "A wealthy inventor creates an advanced armored suit and becomes a hero.",
        "rating": 7.9,
        "year": 2008
    },
    {
        "title": "Avengers: Endgame",
        "genre": "Action Adventure Science Fiction",
        "description": "Heroes unite to reverse the destruction caused by a powerful enemy.",
        "rating": 8.4,
        "year": 2019
    },
    {
        "title": "Titanic",
        "genre": "Romance Drama",
        "description": "A young couple falls in love aboard a famous ocean liner.",
        "rating": 7.9,
        "year": 1997
    },
    {
        "title": "The Notebook",
        "genre": "Romance Drama",
        "description": "A couple experiences a lifelong love story filled with challenges.",
        "rating": 7.8,
        "year": 2004
    },
    {
        "title": "La La Land",
        "genre": "Romance Musical Drama",
        "description": "A musician and an actress pursue their dreams while falling in love.",
        "rating": 8.0,
        "year": 2016
    },
    {
        "title": "Pride and Prejudice",
        "genre": "Romance Drama",
        "description": "A young woman navigates family expectations and unexpected love.",
        "rating": 7.8,
        "year": 2005
    },
    {
        "title": "The Conjuring",
        "genre": "Horror Mystery Thriller",
        "description": "Paranormal investigators help a family experiencing supernatural events.",
        "rating": 7.5,
        "year": 2013
    },
    {
        "title": "A Quiet Place",
        "genre": "Horror Science Fiction Drama",
        "description": "A family survives in silence while hiding from dangerous creatures.",
        "rating": 7.5,
        "year": 2018
    },
    {
        "title": "Get Out",
        "genre": "Horror Mystery Thriller",
        "description": "A young man discovers disturbing secrets while visiting his girlfriend's family.",
        "rating": 7.8,
        "year": 2017
    },
    {
        "title": "Toy Story",
        "genre": "Animation Adventure Comedy Family",
        "description": "Toys come to life and experience friendship and adventure.",
        "rating": 8.3,
        "year": 1995
    },
    {
        "title": "Finding Nemo",
        "genre": "Animation Adventure Family",
        "description": "A father crosses the ocean to find his missing son.",
        "rating": 8.2,
        "year": 2003
    },
    {
        "title": "Coco",
        "genre": "Animation Fantasy Family",
        "description": "A young musician enters the land of the dead to understand his family history.",
        "rating": 8.4,
        "year": 2017
    },
    {
        "title": "The Hangover",
        "genre": "Comedy Adventure",
        "description": "Friends search for a missing groom after a chaotic night in Las Vegas.",
        "rating": 7.7,
        "year": 2009
    },
    {
        "title": "Home Alone",
        "genre": "Comedy Family",
        "description": "A child protects his home from two burglars during Christmas.",
        "rating": 7.7,
        "year": 1990
    },
    {
        "title": "Jurassic Park",
        "genre": "Adventure Science Fiction Thriller",
        "description": "Scientists create a park containing genetically recreated dinosaurs.",
        "rating": 8.2,
        "year": 1993
    },
    {
        "title": "The Lord of the Rings",
        "genre": "Fantasy Adventure Drama",
        "description": "A group begins a dangerous journey to destroy a powerful ring.",
        "rating": 8.9,
        "year": 2001
    },
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "genre": "Fantasy Adventure Family",
        "description": "A young boy discovers that he is a wizard and attends a magical school.",
        "rating": 7.7,
        "year": 2001
    }
]

movies = pd.DataFrame(movie_data)

print(f"Dataset created successfully with {len(movies)} movies.")
movies.head(30)

print("Dataset dimensions:", movies.shape)
print("\nColumn names:")
print(list(movies.columns))

print("\nMissing values:")
print(movies.isnull().sum())

print("\nDataset information:")
movies.info()

movies.to_csv("movies.csv", index=False)

print("The dataset was saved successfully as movies.csv.")

# Replace missing values with empty strings
movies["genre"] = movies["genre"].fillna("")
movies["description"] = movies["description"].fillna("")

# Combine the movie genre and description
movies["combined_features"] = (
    movies["genre"] + " " + movies["description"]
)

movies[["title", "combined_features"]].head()

"""## 3. Building the Recommendation Model

The system uses TF-IDF vectorization and cosine similarity.

TF-IDF assigns numerical importance to words based on how frequently they appear in one movie's features compared with their frequency across the entire dataset. Cosine similarity then measures the similarity between the resulting movie vectors. A higher cosine-similarity score indicates that two movies have more content characteristics in common.
"""



# Create the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer(
    stop_words="english",
    lowercase=True
)

# Convert the combined movie features into numerical vectors
tfidf_matrix = tfidf_vectorizer.fit_transform(
    movies["combined_features"]
)

print("TF-IDF matrix created successfully.")
print("TF-IDF matrix dimensions:", tfidf_matrix.shape)

# Calculate similarity between every pair of movies
cosine_similarity_matrix = cosine_similarity(tfidf_matrix)

print("Cosine similarity matrix created successfully.")
print(
    "Cosine similarity matrix dimensions:",
    cosine_similarity_matrix.shape
)

"""## 4. Recommendation Function

The recommendation function identifies the selected movie, retrieves its cosine-similarity scores, sorts the movies from most similar to least similar, excludes the selected movie itself, and returns the requested number of recommendations.
"""

def recommend_movies(movie_title, number_of_recommendations=5):
    """
    Generate movie recommendations using cosine-similarity scores.

    Parameters:
        movie_title: The title selected by the user.
        number_of_recommendations: Number of recommendations to return.

    Returns:
        A pandas DataFrame containing ranked movie recommendations.
    """

    matching_movies = movies.index[
        movies["title"] == movie_title
    ].tolist()

    if not matching_movies:
        return pd.DataFrame({
            "Message": ["The selected movie was not found."]
        })

    selected_movie_index = matching_movies[0]

    similarity_scores = list(
        enumerate(
            cosine_similarity_matrix[selected_movie_index]
        )
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda item: item[1],
        reverse=True
    )

    recommendations = []

    for movie_index, similarity_score in similarity_scores:
        if movie_index == selected_movie_index:
            continue

        movie = movies.iloc[movie_index]

        recommendations.append({
            "Rank": len(recommendations) + 1,
            "Movie": movie["title"],
            "Genre": movie["genre"],
            "Year": int(movie["year"]),
            "Rating": float(movie["rating"]),
            "Similarity (%)": round(
                float(similarity_score) * 100,
                2
            )
        })

        if len(recommendations) == number_of_recommendations:
            break

    return pd.DataFrame(recommendations)

interstellar_recommendations = recommend_movies(
    "Interstellar",
    5
)

interstellar_recommendations

titanic_recommendations = recommend_movies(
    "Titanic",
    5
)

titanic_recommendations

"""## 5. Interactive User Interface

The interface allows users to choose a movie from a dropdown menu, specify the desired number of recommendations, and generate results by clicking a button. This provides a simple conversational-style interaction with the recommendation model.
"""

# Create the application title
application_title = widgets.HTML(
    value="""
    <h2>🎬 Smart Movie Recommendation System</h2>
    <p>
    Select a movie you enjoyed and the system will recommend
    similar movies using TF-IDF and cosine similarity.
    </p>
    """
)

# Create movie-selection dropdown
movie_dropdown = widgets.Dropdown(
    options=sorted(movies["title"].tolist()),
    value="Interstellar",
    description="Movie:",
    disabled=False,
    layout=widgets.Layout(width="600px"),
    style={"description_width": "100px"}
)

# Create recommendation-count slider
recommendation_slider = widgets.IntSlider(
    value=5,
    min=3,
    max=10,
    step=1,
    description="Results:",
    continuous_update=False,
    layout=widgets.Layout(width="600px"),
    style={"description_width": "100px"}
)

# Create recommendation button
recommend_button = widgets.Button(
    description="Generate Recommendations",
    button_style="success",
    tooltip="Click to generate movie recommendations",
    icon="search",
    layout=widgets.Layout(width="300px")
)

# Create output area
recommendation_output = widgets.Output()


def display_recommendations(button):
    """Display recommendations selected through the interface."""

    with recommendation_output:
        clear_output()

        selected_movie = movie_dropdown.value
        recommendation_count = recommendation_slider.value

        selected_details = movies[
            movies["title"] == selected_movie
        ].iloc[0]

        print("=" * 70)
        print(f"SELECTED MOVIE: {selected_movie}")
        print(f"GENRE: {selected_details['genre']}")
        print(f"YEAR: {int(selected_details['year'])}")
        print(f"RATING: {float(selected_details['rating']):.1f}/10")
        print("=" * 70)

        results = recommend_movies(
            selected_movie,
            recommendation_count
        )

        print(
            f"\nTop {recommendation_count} recommendations "
            f"for {selected_movie}:\n"
        )

        display(results)


recommend_button.on_click(display_recommendations)

display(
    application_title,
    movie_dropdown,
    recommendation_slider,
    recommend_button,
    recommendation_output
)

"""## 6. System Evaluation

The system was evaluated using movies from multiple categories, including science fiction, romance, animation, horror, comedy, and fantasy. Testing demonstrated that the recommendation results change based on the genre and description of the selected movie.

For example, selecting *Interstellar* produces recommendations related to science fiction, space exploration, adventure, and drama. Selecting *Titanic* produces recommendations that more strongly emphasize romance and drama. This behavior demonstrates that the content-based model is responding to differences in movie characteristics.
"""



"""## 7. Limitations and Future Improvements

The primary limitation of the prototype is the relatively small dataset. A larger dataset would provide more diverse and accurate recommendations. The model also relies only on content features and does not consider individual user ratings, viewing history, or changing preferences.

Future improvements could include collaborative filtering, user profiles, real-time movie information, natural-language search, voice interaction, and hybrid recommendation techniques. A more advanced version could proactively recommend movies based on a user's previous selections, time of day, viewing patterns, and current interests.
"""



"""## 8. Conclusion

This project demonstrated the development of a working artificial intelligence recommendation system. The system used TF-IDF to transform movie information into numerical vectors and cosine similarity to identify related items. An interactive interface allowed users to select a movie and generate ranked recommendations.

Developing the system provided practical experience with data preparation, natural-language processing, similarity measurement, interface design, model testing, and source-code documentation. The project also demonstrated how intelligent assistants can move beyond answering direct questions and provide increasingly personalized and proactive recommendations.
"""
